# Tell Python build system about required tools.
# Leave unchanged.

[build-system]
requires = [
    "setuptools",
    "wheel",
    "matploblib",
    "numpy"
]
build-backend = "setuptools.build_meta"
